# Generated by Django 3.1.1 on 2020-10-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField(max_length=50)),
                ('ESalary', models.IntegerField()),
                ('EDesignation', models.CharField(max_length=80)),
                ('EAddrs', models.CharField(max_length=120)),
            ],
        ),
    ]
