# Generated by Django 3.1.1 on 2020-10-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_model',
            name='Eid',
            field=models.IntegerField(),
        ),
    ]
