apiVersion: v1
kind: Secret
metadata: {name: fastapi-secret, namespace: fastapi}
type: Opaque
stringData:
  DATABASE_URL: postgresql+asyncpg://app:CHANGE_ME@postgres.example:5432/app
  JWT_SECRET_KEY: CHANGE_ME
