# Generated by Django 3.1.1 on 2020-10-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpId', models.IntegerField()),
                ('EmpName', models.CharField(max_length=30)),
                ('EmpSal', models.IntegerField()),
                ('EmpAdd', models.CharField(max_length=30)),
            ],
        ),
    ]
