# Generated by Django 3.1.2 on 2020-11-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=40)),
                ('Clogo', models.FileField(blank='True', null='True', upload_to='')),
                ('Ccity', models.CharField(max_length=40)),
            ],
        ),
    ]
