# Generated by Django 3.1.1 on 2020-10-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empid', models.IntegerField()),
                ('EmpName', models.CharField(max_length=50)),
                ('Empsal', models.IntegerField()),
                ('Empadd', models.CharField(max_length=50)),
            ],
        ),
    ]
